_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
                - 100
            "2":
                - 1
                - 55
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
amp:
    value: true
batch_size:
    value: 1
img_scale:
    value: 0.5
learning_rate:
    value: 1e-05
n_epochs:
    value: 5
save_checkpoint:
    value: true
val_percent:
    value: 0.1
